config/routes.rb
Rails.application.routes.draw do
  get 'hamacs/index'

  devise_for :users
  root to: 'pages#home'


  resources :hamacs, only: [ :index, :show ] do
    resources :bookings, only: [ :new, :create]
  end

  resource :profile, only: [ :show ]

  namespace :traveler do
    resources :bookings, only: [ :index ] do
      member do
        patch 'cancel'
      end
    end


  end

  namespace :owner do
    resources :hamacs

    resources :bookings, only: [ :index ] do
      member do
        patch 'accept'
        patch 'refuse'
      end
    end
  end

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hamac
  validates :status, inclusion: { in: ["cancelled", "pending", "accepted", "refused"], allow_nil: false }
end

app/models/hamac.rb
class Hamac < ApplicationRecord
  has_many :bookings
  belongs_to :user
  validates :description, presence: true
   # validates :picture, presence: true
  validates :price, presence: true
  validates :address, presence: true
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :hamacs
  has_many :bookings_as_owner, through: :hamacs, source: :bookings
  has_many :bookings
  validates :email, presence: true, uniqueness: true
  mount_uploader :picture, ProfilePictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :description, :picture, :picture_cache])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    # devise_parameter_sanitizer.permit(:sign_in) do |user_params|
    #   user_params.permit(:username, :email)
    # end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  def create
    @booking = Booking.new(hamac_id: params[:hamac_id], user: current_user, status: "pending")
    @booking.save
    redirect_to traveler_bookings_path
  end



end

app/controllers/hamacs_controller.rb
class HamacsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
    if params[:search] != nil
      @hamacs = Hamac.where( "address ILike ?",  "%#{params[:search]}%").where.not(user: current_user)
    else
      @hamacs = Hamac.where.not(user: current_user)
    end
    # @hamacs = Hamac.where.not(latitude: nil, longitude: nil)

    # @hash = Gmaps4rails.build_markers(@flats) do |hamac, marker|
    #   marker.lat hamac.latitude
    #   marker.lng hamac.longitude
    #   # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    # end
  end

  def show
    @hamac = Hamac.find(params[:id])
    @hamac_coordinates = [{ lat: @hamac.latitude, lng: @hamac.longitude }]
    # binding.pry
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController

  def index
    @bookings_for_owner = current_user.bookings_as_owner
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save!
    redirect_to owner_bookings_path
  end

  def refuse
    @booking = Booking.find(params[:id])
    @booking.status = "refused"
    @booking.save!
    redirect_to owner_bookings_path
  end

end

app/controllers/owner/hamacs_controller.rb
class Owner::HamacsController < ApplicationController

  def index
    @hamacs = current_user.hamacs
  end

  def new
    @hamac = Hamac.new
  end

  def create
    @hamac = Hamac.new(hamac_params)
    @hamac.user = current_user
    if @hamac.save
      redirect_to owner_hamacs_path
    else
      render :new
    end
  end

  def show
    @hamac = Hamac.find(params[:id])
  end

  def edit
    @hamac = Hamac.find(params[:id])
  end

  def update
    @hamac.update(hamac_params)
    redirect_to owner_hamac_path(@hamac)
  end

  def destroy
    @hamac.destroy
    redirect_to owner_hamacs_path
  end

  def self.search(search)
    where()
  end

private

  def hamac_params
    params.require(:hamac).permit(:name, :description, :photo, :photo_cache, :price, :disponibility, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @hamacs = Hamac.all.shuffle[0..5]
  end

  def login

  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
skip_before_action :authenticate_user!, only: [:show ]
  def show
    @current_user = current_user
  end
end

app/controllers/traveler/bookings_controller.rb
class Traveler::BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings
  end


  def cancel
    @booking = Booking.find(params[:id])
    @booking.status = "cancelled"
    @booking.save
    redirect_to traveler_bookings_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hamacs/index.html.erb
<div class="wrapper">
  <h1 class="text-center">Your hamacs list</h1>
  <p>Find your hamac everywhere</p>
      <div class="container">
        <div class="row">
          <% @hamacs.each do |hamac| %>
            <div class="col-xs-12 col-sm-4">
                <div class="card">
                <%= link_to hamac_path(hamac) do %>
                  <h3 class="card-name"><%= hamac.name %></h3>
                  <p class="card-price"><%= hamac.price %> €</p>
                  <div class="card-photo-background">
                    <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path hamac.photo, height: 300, width: 400, crop: :fill %>');">
                      <div class="card-category">
                        <% if hamac.disponibility == true %>
                          <span class="label label-success">Available</span>
                        <% else %>
                          <span class="label label-danger">Not available</span>
                        <% end %>
                      </div>
                    </div>
                  </div>
                    <!-- à rajouter l'image avatar de l'owner -->
                    <!-- <img src="images/papillard.jpeg" class="avatar"> -->
                    <p class="card-address"><%= hamac.address %></p>
                <% end %>
                </div>
             </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/hamacs/show.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-xs-6">
      <div class="card_show" style="width: 30rem;">
        <div class="show_card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @hamac.photo, height: 300, width: 400, crop: :fill %>');">
<!-- container avec la photo + la map geolocalisation -->
          <% if @hamac.disponibility %>
            <span class="label label-success">Available</span>
          <% else %>
            <span class="label label-danger">Not available</span>
          <% end %>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%=@hamac.name %></li>
        <li class="list-group-item"><%=@hamac.description%></li>
        <li class="list-group-item"><%=@hamac.price%> €</li>
        <li class="list-group-item"><%=@hamac.address%></li>
    <!-- /!\ NEED TO DO THE PATH TO THE BOOKING -->
        <button type="button" class="btn btn-lg btn-danger" data-toggle="modal" data-target="#booking-now">Book it now!</button>
      </ul>
    </div>

<!-- Trigger the modal with a button -->

<!-- Modal -->
<div id="booking-now" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Information about your booking</h4>
      </div>
      <div class="modal-body">
        <h1>You want to book the following Hammmock</h1>
        <ul>
        <%= image_tag @hamac.photo, height: 300, width: 400, crop: :fill %>
        <li class="list-group-item"><%=@hamac.name %></li>
        <li class="list-group-item"><%=@hamac.description%></li>
        <li class="list-group-item"><%=@hamac.price%> €</li>
        <li class="list-group-item"><%=@hamac.address%></li>
        </ul>
        <%= link_to "Confirm Booking!", hamac_bookings_path(@hamac), method: :post, class: "btn btn-danger" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


    <div class="col-xs-6">
      <div id="map" style="width: 80%; height: 400px;"></div>

      <% content_for(:after_js) do %>
          <script>
          $(document).ready(function() {
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(<%= raw @hamac_coordinates.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(4);
              }
            });
          });
          </script>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Hammock rental, Hamakoulele</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_MAPS_API_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag "application" %>

    <%= yield(:after_js) %>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div class="wrapper">
  <h1>Pending Requests</h1>
  <br>
  <br>
  <br>
    <% @bookings_for_owner.each do |booking| %>
      <% if booking.status == "pending" %>
        <ul>
          <div class="row">
            <div class="col-xs-12 col-sm-4 owner-booking-information">
              <li><%= booking.hamac.name %> - <%= booking.status %> - <em>Booked by</em> :
              <%= link_to "#{booking.user.first_name} #{booking.user.last_name}", profile_path %>
        <!--       <a class="btn btn-success" href="">Accept</a>
              <a class="btn btn-danger" href="">Refuse</a> -->
            </div>
            <div class="col-xs-12 col-sm-3 owner-button">
            <%= link_to "Refuse", refuse_owner_booking_path(booking), method: :patch, class: "btn btn-danger" %>
            <%= link_to "Accept", accept_owner_booking_path(booking), method: :patch, class: "btn btn-success" %>
            </div>
            </li>
          </div>
        </ul>
      <% end %>
    <% end %>

  <h1>Accepted Requests</h1>
  <br>
  <br>
  <br>
    <% @bookings_for_owner.each do |booking| %>
      <% if booking.status == "accepted" %>
        <ul>
          <div class="row">
            <div class="col-xs-12 col-sm-4 owner-booking-information">
              <li><%= booking.hamac.name %> - <%= booking.status %> - <em>Booked by</em> :
              <%= link_to "#{booking.user.first_name} #{booking.user.last_name}", profile_path %>
        <!--       <a class="btn btn-success" href="">Accept</a>
              <a class="btn btn-danger" href="">Refuse</a> -->
            </div>
            </li>
          </div>
        </ul>
      <% end %>
    <% end %>

  <h1>Refused Requests</h1>
  <br>
  <br>
  <br>
  <% @bookings_for_owner.each do |booking| %>
    <% if booking.status == "refused" %>
      <ul>
        <div class="row">
          <div class="col-xs-12 col-sm-4 owner-booking-information">
            <li><%= booking.hamac.name %> - <%= booking.status %> - <em>Booked by</em> :
            <%= link_to "#{booking.user.first_name} #{booking.user.last_name}", profile_path %>
      <!--       <a class="btn btn-success" href="">Accept</a>
            <a class="btn btn-danger" href="">Refuse</a> -->
          </div>
          </li>
        </div>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/owner/hamacs/edit.html.erb
<div class="wrapper">
  <h1>Your Hamac</h1>

  <%= simple_form_for @hamac do |hamac| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.submit "Add the Hamac", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/owner/hamacs/index.html.erb
<div class="wrapper">
  <div class="add-button">
  <%= link_to new_owner_hamac_path do %>
    <i class="fa fa-plus-circle" aria-hidden="true"></i>
  <% end %>
  </div>
    <h1 class="text-center">My Hamacs</h1>
    <div class="container">
      <div class="row">
        <% @hamacs.each do |hamac| %>
          <div class="col-xs-12 col-sm-4">
            <div class="card">
              <h4 class="card-name"><%= hamac.name %></h4>
              <p class="card-price"><%= hamac.price %> €</p>
              <div class="card-photo-background">
                <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path hamac.photo, height: 300, width: 400, crop: :fill %>');">
                  <div class="card-category">
                    <% if hamac.disponibility %>
                      <span class="label label-success">Available</span>
                    <% else %>
                      <span class="label label-danger">Not available</span>
                    <% end %>
                  </div>
                </div>
              </div>
              <p class="card-address"><%= hamac.address %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to "check my bookings", owner_bookings_path, class: "text-center" %>
  </div>
</div>

app/views/owner/hamacs/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="form-container">
      <h1>New Hamac</h1>
      <%= simple_form_for @hamac, url: owner_hamacs_path do |h| %>
        <%= h.input :name, placeholder: "Hamac's name" %>
        <%= h.input :photo, placeholder: "Upload image" %>
        <%= h.input :photo_cache, as: :hidden %>
        <%= h.input :price, placeholder: "Your Price" %>
        <%= h.input :description, placeholder: "Describe your Hamac" %>
        <%= h.input :address, placeholder: "Where it can be picked" %>
        <%= h.submit "Add the Hamac", class: "btn btn-primary" %>
      <% end %>
    </div>
  <div>
<div>

app/views/owner/hamacs/show.html.erb
<div class="wrapper">
  <h1><%= hamac.name %></h1>


  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <%= image_tag hamac.photo.url %>
        <%= hamac.price %>
      </div>
      <div class="col-xs-6">
        <%= hamac.disponibility %>
        <%= hamac.address %>
      </div>
      <div class="col-xs-12">
        <%= hamac.description %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- #big home photo -->
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'home-page.jpg'%>) ">
  <div class="banner-content">
    <h1>Discover the best place to rest in a Hamac</h1>
    <p> discover our best hamacs</p>
    <div class="searchbar-flex">
      <form method="get" action="/hamacs" class="search_form-flex">
        <div class="search_input-flex">
          <label for="hamac_name" id="label_city">Where?</label>
          <input type="text" id="search" name="search" placeholder="hamacs location" id="hamac_name">
        </div>
        <div class="search_input-flex">
          <input type="submit" value="Search"  class=" btn-danger">
        </div>
      </form>
      <%= link_to 'List all hamacs', hamacs_path %>
    </div>
  </div>
</div>

<!-- #suggestion carts -->
<div class="wrapper">
  <h1 class="text-center">Some Hamacs Suggestions</h1>
    <div class="container">
      <div class="row">
        <% @hamacs.each do |hamac| %>
          <div class="col-xs-12 col-sm-4">
            <div class="card">
              <%= link_to hamac_path(hamac) do %>
                <h3 class="card-name"><%= hamac.name %></h3>
                <p class="card-price"><%= hamac.price %> €</p>
                <div class="card-photo-background">
                  <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path hamac.photo, height: 400, width: 400, crop: :fill %>');">
                    <div class="card-category">
                      <% if hamac.disponibility %>
                        <span class="label label-success">Available</span>
                      <% else %>
                        <span class="label label-danger">Not available</span>
                      <% end %>
                    </div>
                  </div>
                </div>
                <!-- <img src="images/papillard.jpeg" class="avatar"> -->
              <p class="card-address"><%= hamac.address %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="wrapper">
  <h1>My Profile</h1>
  <div class="row">
    <div class="col-xs-6">
      <h4><strong>First name: </strong></h4><%= @current_user.first_name %>
      <h4><strong>Last name: </strong></h4><%= @current_user.last_name %>
      <h4><strong>Address: </strong></h4><%= @current_user.address %>
      <h4><strong>Description: </strong></h4><%= @current_user.description %>
    </div>
    <div class="col-xs-6">
      <% if current_user.picture.url %>
          <div class="show_card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @current_user.picture, height: 300, width: 400, crop: :fill %>');">
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-hamakoulele">
  <!-- Logo -->
  <a href="/" class="navbar-hamakoulele-brand">
    <%= image_tag 'hamac-palmier.png' %>
  </a>

  <!-- title of the page -->
  <div class="navbar-title">
    <h1>HAMAKOULELE</h1>
    </div>
  <!-- Right Navigation -->
  <div class="navbar-hamakoulele-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-hamakoulele-search">
      <input type="text" class="navbar-hamakoulele-search-input" placeholder="Search something">
      <button type="submit" class="navbar-hamakoulele-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->


    <!-- Text link -->
    <% if current_user %>
      <div class="navbar-hamakoulele-item">
        <div class="dropdown">
          <% if current_user.picture.present? %>
            <%= cl_image_tag current_user.picture.url , class: "avatar dropdown-toggle", id: "navbar-hamakoulele-menu", data: { toggle: "dropdown" } %>
          <% else %>
            <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-hamakoulele-menu" data-toggle="dropdown">
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-hamakoulele-dropdown-menu">
            <li><%= link_to "My Profile", profile_path  %></li>
            <li><%= link_to "My Bookings", traveler_bookings_path %></li>
            <li><%= link_to "My Hamacs", owner_hamacs_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "navbar-hamakoulele-item navbar-hamakoulele-link" %>
    <% end %>
    <!-- Notification link-->


    <!-- Profile picture and dropdown -->


    <!-- Button (call-to-action) -->
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-hamakoulele-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-hamakoulele-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/traveler/bookings/index.html.erb
<div class="wrapper">
<h1>Bookings confirmed</h1>
  <ul>
    <% @bookings.each do |booking| %>
      <% if booking.status == "accepted" %>
        <div class="row">
          <div class="col-xs-12 col-sm-4 owner-booking-information">
            <h3> <%= booking.hamac.name %> - <%= booking.hamac.user.first_name %></h3>
          </div>
          <div class="col-xs-12 col-sm-4 owner-booking-information">
            <%= link_to "Cancel", cancel_traveler_booking_path(booking), method: :patch, class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </ul>

  <h1>Bookings pending</h1>
  <ul>
    <% @bookings.each do |booking| %>
      <% if booking.status == "pending" %>
        <div class="row">
          <div class="col-xs-12 col-sm-4 owner-booking-information">
            <h3> <%= booking.hamac.name %> - <%= booking.hamac.user.first_name %></h3>
          </div>
          <div class="col-xs-12 col-sm-4 owner-booking-information">
            <%= link_to "Cancel", cancel_traveler_booking_path(booking), method: :patch, class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </ul>
</div>